codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  unit:
    paths:
      - src/gm_chatbot/
    carryforward: true
    after_n_builds: 1
  integration:
    paths:
      - src/gm_chatbot/
    carryforward: true
    after_n_builds: 1

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
